In [33]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from pathlib import Path

DATA     = Path("../data/processed")
REPORTS  = Path("../reports")
REPORTS.mkdir(exist_ok=True)

RF = 0.065
TRADING_DAYS = 252

print("✅ Libraries loaded")

✅ Libraries loaded

In [34]:
nav = pd.read_csv(DATA / "nav_history_clean.csv")

print(nav.shape)
nav.head()

(46000, 3)

   amfi_code        date       nav
0     100016  2022-01-03  520.4608
1     100016  2022-01-04  515.0971
2     100016  2022-01-05  521.7239
3     100016  2022-01-06  515.7880
4     100016  2022-01-07  515.1639

In [35]:
nav = nav.sort_values(
    ["amfi_code", "date"]
)

nav.head()

   amfi_code        date       nav
0     100016  2022-01-03  520.4608
1     100016  2022-01-04  515.0971
2     100016  2022-01-05  521.7239
3     100016  2022-01-06  515.7880
4     100016  2022-01-07  515.1639

In [36]:
nav["daily_return"] = nav.groupby(
    "amfi_code"
)["nav"].pct_change()

nav.head()

   amfi_code        date       nav  daily_return
0     100016  2022-01-03  520.4608           NaN
1     100016  2022-01-04  515.0971     -0.010306
2     100016  2022-01-05  521.7239      0.012865
3     100016  2022-01-06  515.7880     -0.011377
4     100016  2022-01-07  515.1639     -0.001210

In [37]:
nav["daily_return"].describe()

count    45960.000000
mean         0.000631
std          0.010290
min         -0.058102
25%         -0.005042
50%          0.000340
75%          0.006324
max          0.064713
Name: daily_return, dtype: float64

In [38]:
cagr_df = nav.groupby("amfi_code").agg(
    start_nav=("nav", "first"),
    end_nav=("nav", "last"),
    start_date=("date", "first"),
    end_date=("date", "last")
)

cagr_df["years"] = (
    cagr_df["end_date"] - cagr_df["start_date"]
).dt.days / 365

cagr_df["cagr"] = (
    (cagr_df["end_nav"] / cagr_df["start_nav"])
    ** (1 / cagr_df["years"])
    - 1
)

cagr_df[["cagr"]].head()

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [ ]:
sharpe_df = nav.groupby("amfi_code")["daily_return"].agg(
    mean_return="mean",
    std_return="std"
)

sharpe_df["sharpe_ratio"] = (
    (sharpe_df["mean_return"] * TRADING_DAYS - RF)
    /
    (sharpe_df["std_return"] * np.sqrt(TRADING_DAYS))
)

sharpe_df[["sharpe_ratio"]].head()

           sharpe_ratio
amfi_code
100016        -0.201517
100025        -0.567095
100033         1.093699
101206         1.027213
101207         0.162661

In [ ]:
sharpe_df = nav.groupby("amfi_code")["daily_return"].agg(
    mean_return="mean",
    std_return="std"
)

sharpe_df["sharpe_ratio"] = (
    (sharpe_df["mean_return"] * TRADING_DAYS - RF)
    /
    (sharpe_df["std_return"] * np.sqrt(TRADING_DAYS))
)

sharpe_df[["sharpe_ratio"]].head()

NameError: name 'nav' is not defined

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from pathlib import Path

DATA = Path("../data/processed")

RF = 0.065
TRADING_DAYS = 252

In [ ]:
nav = pd.read_csv(DATA / "nav_history_clean.csv")

In [ ]:
print(nav.shape)
nav.head()

(46000, 3)

   amfi_code        date       nav
0     100016  2022-01-03  520.4608
1     100016  2022-01-04  515.0971
2     100016  2022-01-05  521.7239
3     100016  2022-01-06  515.7880
4     100016  2022-01-07  515.1639

In [ ]:
nav["date"] = pd.to_datetime(nav["date"])

In [ ]:
nav["daily_return"] = (
    nav.groupby("amfi_code")["nav"]
       .pct_change()
)

In [ ]:
sharpe_df = nav.groupby("amfi_code")["daily_return"].agg(
    mean_return="mean",
    std_return="std"
)

sharpe_df["sharpe_ratio"] = (
    (sharpe_df["mean_return"] * TRADING_DAYS - RF)
    /
    (sharpe_df["std_return"] * np.sqrt(TRADING_DAYS))
)

sharpe_df[["sharpe_ratio"]].head()

           sharpe_ratio
amfi_code
100016        -0.201517
100025        -0.567095
100033         1.093699
101206         1.027213
101207         0.162661

In [ ]:
print(nav.columns.tolist())

['amfi_code', 'date', 'nav', 'daily_return']

In [ ]:
import os
print(os.listdir(DATA))

['.gitkeep', 'aum_by_fund_house_clean.csv', 'benchmark_indices_clean.csv', 'category_inflows_clean.csv', 'fund_master_clean.csv', 'industry_folio_count_clean.csv', 'investor_transactions_clean.csv', 'monthly_sip_inflows_clean.csv', 'nav_history_clean.csv', 'portfolio_holdings_clean.csv', 'scheme_performance_clean.csv']

In [ ]:
benchmark = pd.read_csv(
    DATA / "benchmark_indices_clean.csv"
)

benchmark.head()

         date index_name  close_value
0  2022-01-03    NIFTY50     17492.79
1  2022-01-04    NIFTY50     17689.64
2  2022-01-05    NIFTY50     17835.05
3  2022-01-06    NIFTY50     17878.51
4  2022-01-07    NIFTY50     17759.15

In [ ]:
print(benchmark.columns.tolist())

['date', 'index_name', 'close_value']

In [ ]:
benchmark.head()

         date index_name  close_value
0  2022-01-03    NIFTY50     17492.79
1  2022-01-04    NIFTY50     17689.64
2  2022-01-05    NIFTY50     17835.05
3  2022-01-06    NIFTY50     17878.51
4  2022-01-07    NIFTY50     17759.15

In [ ]:
benchmark["date"] = pd.to_datetime(benchmark["date"])

In [ ]:
nifty100 = benchmark[
    benchmark["index_name"] == "NIFTY100"
].copy()

In [ ]:
nifty100["benchmark_return"] = (
    nifty100["close_value"]
    .pct_change()
)

In [ ]:
nifty100.head()

           date index_name  close_value  benchmark_return
1150 2022-01-03   NIFTY100     17778.24               NaN
1151 2022-01-04   NIFTY100     17537.52         -0.013540
1152 2022-01-05   NIFTY100     17607.73          0.004003
1153 2022-01-06   NIFTY100     17556.05         -0.002935
1154 2022-01-07   NIFTY100     17664.02          0.006150

In [ ]:
nav["date"] = pd.to_datetime(nav["date"])

In [ ]:
from scipy.stats import linregress

In [ ]:
alpha_beta = []

for code, group in nav.groupby("amfi_code"):

    merged = pd.merge(
        group[["date", "daily_return"]],
        nifty100[["date", "benchmark_return"]],
        on="date",
        how="inner"
    ).dropna()

    if len(merged) < 30:
        continue

    slope, intercept, r, p, se = linregress(
        merged["benchmark_return"],
        merged["daily_return"]
    )

    alpha_beta.append([
        code,
        intercept * 252,
        slope
    ])

alpha_beta_df = pd.DataFrame(
    alpha_beta,
    columns=["amfi_code", "alpha", "beta"]
)

alpha_beta_df.head()

   amfi_code     alpha      beta
0     100016  0.037476 -0.058268
1     100025  0.042818  0.001158
2     100033  0.271954  0.005104
3     101206  0.213998  0.021086
4     101207  0.108971 -0.065289

In [ ]:
alpha_beta_df.to_csv(
    REPORTS / "alpha_beta.csv",
    index=False
)

In [ ]:
mdd_list = []

for code, group in nav.groupby("amfi_code"):

    group = group.sort_values("date")

    running_max = group["nav"].cummax()

    drawdown = (
        group["nav"] / running_max
    ) - 1

    mdd = drawdown.min()

    mdd_list.append([
        code,
        mdd
    ])

mdd_df = pd.DataFrame(
    mdd_list,
    columns=["amfi_code", "max_drawdown"]
)

mdd_df.head()

   amfi_code  max_drawdown
0     100016     -0.247344
1     100025     -0.043083
2     100033     -0.162172
3     101206     -0.112916
4     101207     -0.354469

In [ ]:
scorecard = (
    cagr_df[["cagr"]]
    .merge(
        sharpe_df[["sharpe_ratio"]],
        left_index=True,
        right_index=True
    )
    .merge(
        alpha_beta_df[["alpha"]],
        left_index=True,
        right_on="amfi_code"
    )
    .merge(
        mdd_df,
        left_index=True,
        right_on="amfi_code"
    )
)

NameError: name 'cagr_df' is not defined

In [ ]:
cagr_df = nav.groupby("amfi_code").agg(
    start_nav=("nav", "first"),
    end_nav=("nav", "last"),
    start_date=("date", "first"),
    end_date=("date", "last")
)

cagr_df["years"] = (
    cagr_df["end_date"] - cagr_df["start_date"]
).dt.days / 365

cagr_df["cagr"] = (
    (cagr_df["end_nav"] / cagr_df["start_nav"])
    ** (1 / cagr_df["years"])
    - 1
)

cagr_df[["cagr"]].head()

               cagr
amfi_code
100016     0.026352
100025     0.044551
100033     0.300997
101206     0.235205
101207     0.079331

In [ ]:
print("cagr_df:", "cagr_df" in globals())
print("sharpe_df:", "sharpe_df" in globals())
print("sortino_df:", "sortino_df" in globals())
print("alpha_beta_df:", "alpha_beta_df" in globals())
print("mdd_df:", "mdd_df" in globals())

cagr_df: True
sharpe_df: True
sortino_df: False
alpha_beta_df: True
mdd_df: True

In [ ]:
sortino_list = []

for code, group in nav.groupby("amfi_code"):

    downside = group.loc[
        group["daily_return"] < 0,
        "daily_return"
    ]

    downside_std = downside.std()

    mean_return = group["daily_return"].mean()

    sortino = (
        (mean_return * TRADING_DAYS - RF)
        /
        (downside_std * np.sqrt(TRADING_DAYS))
    )

    sortino_list.append(
        [code, sortino]
    )

sortino_df = pd.DataFrame(
    sortino_list,
    columns=["amfi_code", "sortino_ratio"]
)

sortino_df.head()

   amfi_code  sortino_ratio
0     100016      -0.351047
1     100025      -0.941821
2     100033       1.829134
3     101206       1.799563
4     101207       0.276644

In [ ]:
print("sortino_df:", "sortino_df" in globals())

sortino_df: True

In [ ]:
print("cagr_df:", "cagr_df" in globals())
print("sharpe_df:", "sharpe_df" in globals())
print("alpha_beta_df:", "alpha_beta_df" in globals())
print("mdd_df:", "mdd_df" in globals())
print("sortino_df:", "sortino_df" in globals())

cagr_df: True
sharpe_df: True
alpha_beta_df: True
mdd_df: True
sortino_df: True

In [ ]:
print(cagr_df.columns)
print(sharpe_df.columns)
print(alpha_beta_df.columns)
print(mdd_df.columns)

Index(['start_nav', 'end_nav', 'start_date', 'end_date', 'years', 'cagr'], dtype='str')
Index(['mean_return', 'std_return', 'sharpe_ratio'], dtype='str')
Index(['amfi_code', 'alpha', 'beta'], dtype='str')
Index(['amfi_code', 'max_drawdown'], dtype='str')

In [43]:
# Make sure dates are datetime
cagr_df["start_date"] = pd.to_datetime(cagr_df["start_date"])
cagr_df["end_date"] = pd.to_datetime(cagr_df["end_date"])

# Calculate years
cagr_df["years"] = (
    cagr_df["end_date"] - cagr_df["start_date"]
).dt.days / 365

# Calculate CAGR
cagr_df["cagr"] = (
    (cagr_df["end_nav"] / cagr_df["start_nav"])
    ** (1 / cagr_df["years"])
    - 1
)

cagr_df.head()

           start_nav   end_nav start_date   end_date    years      cagr
amfi_code
100016      520.4608  583.6113 2022-01-03 2026-05-29  4.40274  0.026352
100025       26.3169   31.8843 2022-01-03 2026-05-29  4.40274  0.044551
100033      107.3758  342.0072 2022-01-03 2026-05-29  4.40274  0.300997
101206      305.0996  773.2939 2022-01-03 2026-05-29  4.40274  0.235205
101207       38.5736   53.9836 2022-01-03 2026-05-29  4.40274  0.079331

In [44]:
scorecard = (
    cagr_df[["cagr"]]
    .join(sharpe_df[["sharpe_ratio"]])
)

scorecard.head()

               cagr  sharpe_ratio
amfi_code
100016     0.026352     -0.201517
100025     0.044551     -0.567095
100033     0.300997      1.093699
101206     0.235205      1.027213
101207     0.079331      0.162661

In [45]:
scorecard = scorecard.reset_index()

scorecard = scorecard.merge(
    alpha_beta_df[["amfi_code", "alpha"]],
    on="amfi_code",
    how="left"
)

scorecard = scorecard.merge(
    mdd_df[["amfi_code", "max_drawdown"]],
    on="amfi_code",
    how="left"
)

scorecard.head()

   amfi_code      cagr  sharpe_ratio     alpha  max_drawdown
0     100016  0.026352     -0.201517  0.037476     -0.247344
1     100025  0.044551     -0.567095  0.042818     -0.043083
2     100033  0.300997      1.093699  0.271954     -0.162172
3     101206  0.235205      1.027213  0.213998     -0.112916
4     101207  0.079331      0.162661  0.108971     -0.354469

In [46]:
scorecard["return_rank"] = scorecard["cagr"].rank(
    ascending=False
)

scorecard["sharpe_rank"] = scorecard["sharpe_ratio"].rank(
    ascending=False
)

scorecard["alpha_rank"] = scorecard["alpha"].rank(
    ascending=False
)

scorecard["dd_rank"] = scorecard["max_drawdown"].rank(
    ascending=False
)

In [47]:
scorecard["score"] = (
      0.40 * scorecard["return_rank"]
    + 0.30 * scorecard["sharpe_rank"]
    + 0.20 * scorecard["alpha_rank"]
    + 0.10 * scorecard["dd_rank"]
)

In [48]:
scorecard["score"] = (
    scorecard["score"]
    / scorecard["score"].max()
) * 100

In [49]:
top5 = scorecard.sort_values(
    "score",
    ascending=False
).head(5)

top5

,amfi_code,cagr,sharpe_ratio,alpha,max_drawdown,return_rank,sharpe_rank,alpha_rank,dd_rank,score
7,102886,0.011709,-0.205832,0.028969,-0.280011,40.0,36.0,40.0,35.0,100.000000
17,119095,0.015205,-0.075974,0.048016,-0.516778,39.0,33.0,37.0,39.0,96.083551
0,100016,0.026352,-0.201517,0.037476,-0.247344,37.0,35.0,39.0,34.0,95.300261
22,119599,0.020531,-0.057187,0.048824,-0.525742,38.0,32.0,36.0,40.0,93.994778
1,100025,0.044551,-0.567095,0.042818,-0.043083,36.0,39.0,38.0,4.0,89.033943

In [50]:
scorecard.to_csv(
    REPORTS / "fund_scorecard.csv",
    index=False
)

In [51]:
scorecard["return_rank"] = scorecard["cagr"].rank(
    ascending=False
)

scorecard["sharpe_rank"] = scorecard["sharpe_ratio"].rank(
    ascending=False
)

scorecard["alpha_rank"] = scorecard["alpha"].rank(
    ascending=False
)

# Less negative drawdown is better
scorecard["dd_rank"] = scorecard["max_drawdown"].rank(
    ascending=False
)

In [52]:
n = len(scorecard)

scorecard["return_score"] = n - scorecard["return_rank"] + 1
scorecard["sharpe_score"] = n - scorecard["sharpe_rank"] + 1
scorecard["alpha_score"] = n - scorecard["alpha_rank"] + 1
scorecard["dd_score"] = n - scorecard["dd_rank"] + 1

In [53]:
scorecard["score"] = (
      0.40 * scorecard["return_score"]
    + 0.30 * scorecard["sharpe_score"]
    + 0.20 * scorecard["alpha_score"]
    + 0.10 * scorecard["dd_score"]
)

In [54]:
scorecard["score"] = (
    scorecard["score"]
    / scorecard["score"].max()
) * 100

In [55]:
top5 = scorecard.sort_values(
    "score",
    ascending=False
).head(5)

top5

,amfi_code,cagr,sharpe_ratio,alpha,max_drawdown,return_rank,sharpe_rank,alpha_rank,dd_rank,score,return_score,sharpe_score,alpha_score,dd_score
34,148567,0.309499,1.448291,0.269838,-0.112657,5.0,1.0,7.0,8.0,100.000000,36.0,40.0,34.0,33.0
25,120505,0.328016,1.180101,0.292636,-0.181885,1.0,5.0,3.0,25.0,98.630137,40.0,36.0,38.0,16.0
30,120843,0.308833,1.306744,0.273305,-0.129740,6.0,2.0,5.0,13.0,97.808219,35.0,39.0,36.0,28.0
36,148569,0.319245,1.234930,0.282704,-0.163967,4.0,3.0,4.0,21.0,97.534247,37.0,38.0,37.0,20.0
2,100033,0.300997,1.093699,0.271954,-0.162172,7.0,7.0,6.0,20.0,90.136986,34.0,34.0,35.0,21.0

In [56]:
scorecard.to_csv(
    REPORTS / "fund_scorecard.csv",
    index=False
)

In [57]:
scorecard.to_csv(
    REPORTS / "fund_scorecard.csv",
    index=False
)

print("Fund scorecard saved")

Fund scorecard saved

In [58]:
nifty100["benchmark_return"] = (
    nifty100["close_value"]
    .pct_change()
)

In [59]:
tracking_error_list = []

for code, group in nav.groupby("amfi_code"):

    merged = pd.merge(
        group[["date", "daily_return"]],
        nifty100[["date", "benchmark_return"]],
        on="date",
        how="inner"
    ).dropna()

    if len(merged) < 30:
        continue

    tracking_error = (
        (merged["daily_return"] -
         merged["benchmark_return"])
        .std()
    ) * np.sqrt(TRADING_DAYS)

    tracking_error_list.append(
        [code, tracking_error]
    )

tracking_error_df = pd.DataFrame(
    tracking_error_list,
    columns=[
        "amfi_code",
        "tracking_error"
    ]
)

tracking_error_df.head()

ValueError: You are trying to merge on str and datetime64[us] columns for key 'date'. If you wish to proceed you should use pd.concat

In [60]:
print(nav["date"].dtype)
print(nifty100["date"].dtype)

str
datetime64[us]

In [61]:
nav["date"] = pd.to_datetime(nav["date"])

In [62]:
print(nav["date"].dtype)
print(nifty100["date"].dtype)

datetime64[us]
datetime64[us]

In [63]:
tracking_error_list = []

for code, group in nav.groupby("amfi_code"):

    merged = pd.merge(
        group[["date", "daily_return"]],
        nifty100[["date", "benchmark_return"]],
        on="date",
        how="inner"
    ).dropna()

    if len(merged) < 30:
        continue

    tracking_error = (
        (merged["daily_return"] -
         merged["benchmark_return"])
        .std()
    ) * np.sqrt(TRADING_DAYS)

    tracking_error_list.append(
        [code, tracking_error]
    )

tracking_error_df = pd.DataFrame(
    tracking_error_list,
    columns=["amfi_code", "tracking_error"]
)

tracking_error_df.head()

   amfi_code  tracking_error
0     100016        0.199284
1     100025        0.134535
2     100033        0.228699
3     101206        0.192706
4     101207        0.292117

In [64]:
REPORTS / "benchmark_comparison.png"

WindowsPath('../reports/benchmark_comparison.png')

In [65]:
tracking_error_df.to_csv(
    REPORTS / "tracking_error.csv",
    index=False
)

print("Tracking Error saved")

Tracking Error saved

In [66]:
import os
print(os.listdir(REPORTS))

['.gitkeep', 'alpha_beta.csv', 'fund_scorecard.csv', 'tracking_error.csv']

In [67]:
import os

print("Reports Files:")
print(os.listdir(REPORTS))

Reports Files:
['.gitkeep', 'alpha_beta.csv', 'fund_scorecard.csv', 'tracking_error.csv']